services:
  app:
    build: .
    ports:
      - "8082:8082"
    networks:
        - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: remaladag
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users_authorities_db
    ports:
      - "5434:5432"
    networks:
        - s-network
    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
   s-network:
        driver: bridge
volumes:
  postgres_data: